### ISSUE TITLE
LivePersonModule.swift Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by LayMui** [LivePersonInc/developers-community#1004]
The xcode project was able to build in xcode 11.6
but after upgrade to xcode 12, it has compiler build fail

npx react-native run-ios --configuration Debug --simulator="iPhone 11" --scheme "MyApp_UAT"

DataStore -index-system-modules
/Users/app/node_modules/@dt/react-native-liveperson/ios/LivePersonModule.swift:11:8: error: module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler: /Users/app/ios/Pods/LPMessagingSDK/LPMessagingSDK/LPMessagingSDK.framework/Modules/LPMessagingSDK.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
import LPMessagingSDK

**Comment by j9t** [comment]
Hi @LayMui—thanks for the extreme patience here. Can you confirm this is still an issue?

**Comment by j9t** [comment]
(Closing this one in recognition that this was in need of a response a long time ago. We can reopen as soon as we have confirmation this persists.)
